"""Crear tabla Video con campos URL, title1, title2, title3, summary, transcription

Revision ID: f30a869c35f3
Revises: 
Create Date: 2024-10-22 01:13:50.520860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30a869c35f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('url_video', sa.String(length=255), nullable=False),
    sa.Column('title1', sa.String(length=255), nullable=False),
    sa.Column('title2', sa.String(length=255), nullable=False),
    sa.Column('title3', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('url_video')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
